# Generated by Django 4.2.9 on 2024-02-12 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import puzzle.common.fields
import puzzle.knight_move.fields
import puzzle.models
import puzzle.word_finder.fields
import puzzle.word_ladder.fields
import puzzle.word_square.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=puzzle.models.image_upload_to)),
                ('puzzle_time', models.DateTimeField(auto_now=True)),
                ('puzzle_type', models.CharField(choices=[('knight_move', 'Knight move'), ('pie_slice', 'Pie slice'), ('word_finder', 'Word finder'), ('word_square', 'Word square'), ('word_ladder', 'Word ladder')], max_length=12)),
            ],
            options={
                'ordering': ('-puzzle_time',),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, unique=True)),
                ('size', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('word',),
            },
        ),
        migrations.CreateModel(
            name='KnightMove',
            fields=[
                ('puzzle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.puzzle')),
                ('board', puzzle.common.fields.BoardField(board_class=puzzle.knight_move.fields.Board)),
                ('word', models.CharField(max_length=8, unique=True)),
            ],
            bases=('puzzle.puzzle',),
        ),
        migrations.CreateModel(
            name='PieSlice',
            fields=[
                ('puzzle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.puzzle')),
                ('obfuscated_word', models.CharField(max_length=9)),
                ('word', models.CharField(max_length=9, unique=True)),
            ],
            bases=('puzzle.puzzle',),
        ),
        migrations.CreateModel(
            name='WordFinder',
            fields=[
                ('puzzle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.puzzle')),
                ('board', puzzle.common.fields.BoardField(board_class=puzzle.word_finder.fields.Board)),
                ('hints', models.TextField(blank=True)),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('solution', models.CharField(blank=True, max_length=11)),
                ('words', models.TextField(blank=True)),
            ],
            bases=('puzzle.puzzle',),
        ),
        migrations.CreateModel(
            name='WordLadder',
            fields=[
                ('puzzle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.puzzle')),
                ('board', puzzle.common.fields.BoardField(board_class=puzzle.word_ladder.fields.Board)),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('solution', puzzle.common.fields.BoardField(board_class=puzzle.word_ladder.fields.Board)),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to=puzzle.models.image_upload_to)),
            ],
            bases=('puzzle.puzzle',),
        ),
        migrations.CreateModel(
            name='WordSquare',
            fields=[
                ('puzzle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.puzzle')),
                ('board', puzzle.common.fields.BoardField(board_class=puzzle.word_square.fields.Board)),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('solution', puzzle.common.fields.BoardField(board_class=puzzle.word_square.fields.Board)),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to=puzzle.models.image_upload_to)),
            ],
            bases=('puzzle.puzzle',),
        ),
        migrations.CreateModel(
            name='WordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('token', models.CharField(max_length=1)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='puzzle.word')),
            ],
            options={
                'ordering': ('word', 'index'),
            },
        ),
        migrations.AddConstraint(
            model_name='wordtoken',
            constraint=models.UniqueConstraint(fields=('word', 'index'), name='Unique constraint on word and index'),
        ),
    ]
